name: r_env
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - r-base=4.3.1
  - bioconductor-maftools
  - bioconductor-genomicranges
  - bioconductor-iranges
  - r-dplyr
  - r-ggplot2
  - r-rcolorbrewer
  - r-coin
  - r-cairo
  - r-readr
  - r-tidyr
  - r-r.utils
