OUTDIR: "./nf-macs3"
email: 'annmariya.elayani@gmail.com'
GENOME: "./data/resources-broad-hg38-v0-Homo_sapiens_assembly38.fasta"
ASSEMBLY: ''
GENOME_SIZE: "GRCh38"
SAMPLESHEET: "/Users/ames/chipcallvar.1.0/samplesheet_example.csv"
start_from_vcf: false


# SAMPLESHEET: "/storage/projects/P024_ChIPseq_AE/csv/samplesheet_merged.csv"

# start_from_vcf:  true
# SAMPLESHEET: "/storage/projects/P024_ChIPseq_AE/csv/samplesheet_intermediate.csv"

# start_from_vcf: false
# SAMPLESHEET: "/storage/projects/P024_ChIPseq_AE/csv/samplesheet_cell-lines.csv"
