OUTDIR: '/storage/projects/P024_ChIPseq_AE/nf-test/'
SAMPLESHEET: '/storage/projects/P024_ChIPseq_AE/chipcallvar/example.csv'
step: 'mapping'
tools: 'freebayes'
skip_tools: 'dge'
tpm: '/storage/projects/P034_RNAseq_AE/nf-rnaseq/star_rsem/rsem.merged.gene_tpm.tsv'
email: 'annmariya.elayani@gmail.com'
# genome: './reference/resources-broad-hg38-v0-Homo_sapiens_assembly38.fasta'
# fai: './reference/resources-broad-hg38-v0-Homo_sapiens_assembly38.fasta.fai'
# assembly: 'GRCh38'

# SAMPLESHEET: "/storage/projects/P024_ChIPseq_AE/csv/samplesheet_merged.csv"
# SAMPLESHEET: "/storage/projects/P024_ChIPseq_AE/csv/samplesheet_intermediate.csv"
# SAMPLESHEET: "/storage/projects/P024_ChIPseq_AE/csv/samplesheet_cell-lines.csv"
